### ISSUE TITLE
[Feature] Use make in .travis

### ISSUE THREAD

**Issue by mazarini** [symfony/demo#1013]
"make" with a specific makefile (makefile.travis) and use it for travis.

Its allow :
1) local test easy using make command before commit  (make -f  makefile.travis something) 
2) group action (by example action cond with [[ "$ACTION" == "install" ]]
3) make differents treatment easy using var (make $var)

So can have a .travis more readable and/or  add later phpstan twigcs or php-cs.

Can do a PR if you want see what it can be.

**Comment by javiereguiluz** [comment]
@mazarini thanks for your proposal! However, we have to keep in mind that the "Symfony Demo" project follows as closely as possible all the best and recommended practices for Symfony apps. Although Makefiles were originally part of Symfony 4 practices, they were removed in favor of regular PHP console scripts. So, for that reason, I think it's better to not include a Makefile in this project. That's why we're closing this issue. Thanks.
