### ISSUE TITLE
Demo needs examples of using Services and accessing complex config data 

### ISSUE THREAD

**Issue by sokol-44** [symfony/demo#1021]
It's feature request.
Documentation:
[Services](https://symfony.com/doc/current/service_container.html)
[Config](https://symfony.com/doc/current/configuration.html#accessing-configuration-values)
Lacks full working examples.

**Comment by javiereguiluz** [comment]
You are right ... although we have some services and we use config parameters ... so we do something related to that. In any case, this demo can't display ALL Symfony features because there are too many and some of them are too complex to display them in a demo app. Also, most users of this app are newcomers, so if we add super complex features, instead of thinking *"wow, Symfony is so powerful"* they will probably think *"wow, Symfony is so complex ... let's use something else"*.

That's why I'm closing this as "won't fix" and I hope you understand the reason. Thanks.
