### ISSUE TITLE
Shouldn't package.json define the license as MIT?

### ISSUE THREAD

**Issue by taylankasap** [symfony/demo#1088]
Or is it a better practice to leave it as unlicensed because this repo is not an npm package?

**Comment by stof** [comment]
I don't think we care much about the license field in package.json, given that this is not a npm package, but a project. The license is already stated multiple times in the repo. But this could indeed be changed (I guess this `unlicensed` comes from the Flex recipe, which sets this license because most Symfony projects are not open-source).
