### ISSUE TITLE
[Question] Travis

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/demo#1098]
You have a `.travis.yml` file, thank you for that, I use it as a template.

Could you add comments in `.travis.yml` which explain a little more?

What is unclear for me (as being new to Travis):
- Is there a documentation page where a basic Travis setup for Symfony projects is explained?
- Where should we set the environment?
- Should we set the environment to `test`?
- Your tests seem to use fixtures but the fixtures are not run in your `.travis.yml`, how can that be?

Thank you very much, if you answer the questions here then I will create a PR for the demo app's `.travis.yml` if you want.

**Comment by javiereguiluz** [comment]
Hi Michael:

* Symfony Docs show an an example of Travis CI config for bundles (https://symfony.com/doc/current/bundles/best_practices.html#continuous-integration) You can use it and adapt it to your own app.
* Here you have another article from SymfonyCasts explaining the Travis integration: https://symfonycasts.com/screencast/symfony-bundle/travisci
* About the environment, there's no need to set it to `test` because it's set by Symfony automatically when running tests.

If you have any issues with this, please ask in the `#support` channel of Symfony's Slack (https://symfony.com/slack)

**Comment by michaelKaefer** [comment]
@javiereguiluz Thank you very much!
