### ISSUE TITLE
Select specified version

### ISSUE THREAD

**Issue by nxut** [symfony/demo#1131]
Hi,
How to get repo version of specific symfony version? I want to clone the repo that goes with symfony 3.4. How can I do that?

Thank you

**Comment by gmsantos** [comment]
You may look in the [releases](https://github.com/symfony/demo/releases) page changelog or by searching merged pull requests.

**Comment by rajat315315** [comment]
Are you saying `git checkout 2.*` ?

**Comment by javiereguiluz** [comment]
@nxut this project is not prepared to test it with different Symfony versions. We always update to the latest Symfony version. Sorry!

However, you can do what @gmsantos suggested:

* [1.2.0](https://github.com/symfony/demo/releases/tag/v1.2.0) was the first release using Symfony 4.0.0
* [1.1.1](https://github.com/symfony/demo/releases/tag/v1.1.1) was the previous release, so that's the last one using 3.4.
