### ISSUE TITLE
Simplify front controller

### ISSUE THREAD

**Issue by garak** [symfony/demo#1306]
Instead of
```php
return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```
we could use

```php
return static fn (array $context): Kernel => new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
```

**Comment by gmsantos** [comment]
The index.php file is created from the [symfony framework-bundle recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.4/public/index.php)

You can try to suggest those changes in the recipe instead, but only for Symfony 6.0+, because 5.4 should be compatible with PHP 7.2+, and Arrow functions were introduced in PHP 7.4.

**Comment by GromNaN** [comment]
I think the suggested change doesn't improve readability.

**Comment by javiereguiluz** [comment]
Massimiliano, thanks for sending this proposal.

However, as Gabriel said, this file comes from a Symfony recipe. Since we want this project to 100% align with Symfony code and best practices, we cannot change this ourselves here without changing it first in the recipe.

So, please try to open an issue or PR in the official Symfony repository first and see if it's accepted. Thanks!
