### ISSUE TITLE
Indefinite loop after two weeks

### ISSUE THREAD

**Issue by rkimwebmaster** [symfony/demo#1526]
I have noticed that I can start well a new project. But after around two weeks I always got an indefinite loop.

**Comment by bocharsky-bw** [comment]
You may want to enable redirects interception in Symfony, it will help you to debug what pages are in the loop and probably tweak your business logic, see https://symfony.com/doc/current/reference/configuration/web_profiler.html#intercept-redirects

Also, if you're on a real web server like Nginx/Apache - try to run the built-in Symfony web server first to make sure things works there well. If so, it might be so that you have incorrect server web configuration, take a look at the docs: https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by derrabus** [comment]
You have opened a bug report for the Symfony demo application. Our discussion board might be the better place to ask for help.

https://github.com/symfony/symfony/discussions
