### ISSUE TITLE
Database .env setting parsing broken?

### ISSUE THREAD

**Issue by andig** [symfony/demo#688]
I've updated the `.env` file like this:

	###> doctrine/doctrine-bundle ###
	# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
	# For a sqlite database, use: "sqlite:///%kernel.project_dir%/var/data.db"
	# Set "serverVersion" to your server version to avoid edge-case exceptions and extra database calls
	DATABASE_URL=sqlite:///tmp/blog.sqlite
	###< doctrine/doctrine-bundle ###

That is `sqlite://` and a location in the `/tmp` folder. This is what happens when running the demo:

	~/htdocs/symfony-demo
	❯ php bin/console doctrine:database:create
	boot
	boot
	Could not create database tmp/blog.sqlite for connection named default
	An exception occurred in driver: SQLSTATE[HY000] [14] unable to open database file

Notice the missing `/` on the DB path. Only when using 4x/:

    DATABASE_URL=sqlite:////tmp/blog.sqlite

it actually runs:

	~/htdocs/symfony-demo
	❯ php bin/console doctrine:database:create
	boot
	boot
	Created database /tmp/blog.sqlite for connection named default

Note that this is on OSX.

**Comment by javiereguiluz** [comment]
I'd say this is the expected behavior. When using SQLite, Doctrine requires you to use 3 `/` and then your relative or absolute path. When the path starts with `/`, then you end up with 4 `/`. It's better explained here: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html

Anyway, thanks for reporting things like this because we're making lots of changes lately in this app and we may break things. Thanks!
