### ISSUE TITLE
[Question] Large application structure

### ISSUE THREAD

**Issue by bilel-noomene** [symfony/demo#689]
How to structure a large application with hundreds of files ? 
By type like this
> Controller
>  ---- Module1
>  ---- Module2
> Entity
>  ---- Module1
>  ---- Module2

or by feature like this

> Module1
>  ---- Controller
>  ---- Entity
> Module2
>  ---- Controller
>  ---- Entity

**Comment by jkufner** [comment]
You are missing views, forms, and other components in your question. I would keep entities in a flat structure under the root and rest grouped by feature (the second way). So it would look like this:

    Module1
      -- Controller
      -- templates, resources, ...
    Module2
      -- Controller
      -- templates, resources, ...
    Entity
       -- all entities for both modules

This effectively leaves the model layer outside of the module structure. The reason is the entities are often shared between modules. For example, if you have frontend and backend modules, then both will deal with the same stuff, but in a different way. Moreover, the database is unstructured too (no modules), so it will make your model and database look a like (and easier to navigate).

**Comment by bocharsky-bw** [comment]
Probably it depends on how tight your modules are linked.

**Comment by bilel-noomene** [comment]
@bocharsky-bw The goal is to break down the application into decoupled modules

**Comment by bocharsky-bw** [comment]
Are they really decoupled? Are you sure you won't have hard links between separate modules, like when an entity from one module relates to an entity from another module and so on? Because it's really difficult to achieve, i.e. when you easily can remove a module and your application will still work, but without the feature which was provided by that removed module. If so, probably you need to look in the direction of micro-services that is more complex, otherwise, I think your 1st example in the description of this issue would be fine.

**Comment by bilel-noomene** [comment]
I explain my point of view
Yes, the modules are not fully decoupled. The entities will be surely used in the different places. I think that jkufner's idea of putting them all in one folder is OK. I am also thinking of a shared folder containing common features like validation, uploading, serialization, ...
Otherwise, the coupling between the functionality modules must be minimized, centralized (in a service for example) and in one direction.
The choice of micro-services is difficult to implement at this stage since it's necessary to manage the communication between them. But I'm thinking of an architecture open to micro-services architecture.
I appreciated jkufner's proposal and I think it makes teamwork easier on different modules.
What do you think?

**Comment by jkufner** [comment]
Rather than microservices, I would use bundles. The infrastructure will be much simpler. If you can uninstall bundle without breaking entire application, then it is well decoupled. Also, you can use the same bundle in multiple apps. If you develop some highly modular application for many customers, then it may make sense to use bundles. However, that is not the case for most web applications.

**Comment by javiereguiluz** [comment]
For real decoupling, microservices would be the way to go (but they are hard to develop and maintain unless your team is big and has lots of experience).

For pseudo-decopupling a monolithic app with lots and lots of modules, I agree with @jkufner about using this structure:

```
Module1
  -- Controller
  -- templates, resources, ...
Module2
  -- Controller
  -- templates, resources, ...
Entity
   -- all entities for both modules
```

In any case, let's close this issue because in this repo we only discuss about bugs and features of the Symfony Demo app. For this kind of discussions, it's better to use the Slack chat (see https://symfony.com/support) where you'll find people with lots of experience in architecting apps (and not only Symfony apps). Thanks!
