### ISSUE TITLE
button.navbar-toggle

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#690]
button.navbar-toggle

this Toggle navigation button do not work for me, tested with multiple browsers

installed today, latest fresh version.

**Comment by javiereguiluz** [comment]
This was fixed in #672 and released in 1.1.1 version (https://github.com/symfony/demo/releases). Could you please check if you are using that version? Thanks!

**Comment by lxregistry** [comment]
composer create-project symfony/symfony-demo

maybe you should update it also in https://packagist.org/packages/symfony/symfony-demo ?

**Comment by javiereguiluz** [comment]
@lxregistry you are right! The reason is that this error is fixed but no stable version has been released since that fix. To get the app fully working, execute:

```
composer create-project symfony/symfony-demo:dev-master
```

Adding `dev-master` will be unneeded as soon as we release a new stable version of this application (which will take a bit of time because we're in the middle of the Symfony 4 release process, so we must be careful and in sync with Symfony).

In any case, closing as "fixed". Thanks!
