### ISSUE TITLE
Installing demo with --no-dev doesn't work

### ISSUE THREAD

**Issue by tavy315** [symfony/demo#771]
If I use:
`composer create-project symfony/symfony-demo --no-dev`

I'm getting:
`[Wed Mar 14 17:12:58 2018] PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Dotenv\Dotenv' not found in D:\test\symfony-demo\public\index.php:21`

Is this something normal ?

**Comment by javiereguiluz** [comment]
It's an error ... but it's "normal". It's related to Symfony itself and not this application. The DotEnv component is installed only when not using `--no-dev`. If you don't have `DotEnv` you need to define some env vars in your server (in this case, `APP_ENV` var. See https://github.com/symfony/recipes/blob/a067bebf03a2b244cdf82dd4e3eff52de5320ac2/symfony/framework-bundle/3.3/public/index.php#L11).

That's why you usually don't add `--no-dev` in your local machine (and everything works) but only in your production server, where you are careful to define all the needed env vars.

**Comment by tavy315** [comment]
Let's suppose that this was my production machine, so adding --no-dev was the right way to do it for me.

Meanwhile, the problem is still there, "DotEnv" being required in index.php. Loooking at [https://github.com/symfony/demo/blob/master/README.md], I can't see any reference for required ENV variables for production.

This might be an issue for beginners, as I don't have a problem doing what's needed, but perhaps we can improve the documentation?

**Comment by jkufner** [comment]
I think it would be reasonable to add an explanation to the DotEnv use in index.php. Something like: "Environment variables are not set and DotEnv not installed. See that section in the readme."

**Comment by javiereguiluz** [comment]
@tavy315 I reviewed the Symfony Flex recipes that create the `public/index.php` and I realized that it was recently updated to display a better error message for cases like yours. so in #773 we're updating it. Cheers!

**Comment by tavy315** [comment]
Ok, thanks for looking into it 👍
