### ISSUE TITLE
Filter posts by selected user

### ISSUE THREAD

**Issue by josephpepperson** [symfony/demo#774]
how can i filter posts by selected user?

**Comment by voronkovich** [comment]
@josephpepperson, You can't. It's not a "real" application. We don't need a such feature.

**Comment by javiereguiluz** [comment]
@josephpepperson as @voronkovich said, it's not possible to do that. The reason is that this Symfony Demo app is developed to showcase some Symfony features, but not to make a real and full-featured blog engine like WordPress. So, that's why this feature is not implemented and for the moment we're not planning to add it. Thanks for understanding it 😃
