### ISSUE TITLE
could not find any fixture services to load

### ISSUE THREAD

**Issue by ashfaq17** [symfony/demo#796]
I'm using symfony 3.4.x with doctrine/doctrine-fixtures-bundle": "^3.0

and when I try to run command:  php bin/console doctrine:fixtures:load 
getting the error:
could not find any fixture services to load

**Comment by javiereguiluz** [comment]
@ashfaq17 I'm sorry this issue happened. I'm afraid we cannot help much here because you said that the Symfony version used is 3.4.x ... but this app was updated to 4.x a while ago (and `master` branch uses 4.1 beta 2, the most recent Symfony version possible).

If you want to install the project and load fixtures, run these commands:

```bash
$ composer create-project symfony/symfony-demo
$ cd symfony-demo/
$ ./bin/console doctrine:fixtures:load
```

I hope this is info is useful for you. Cheers!
