### ISSUE TITLE
Incorrect paths when in sub folder

### ISSUE THREAD

**Issue by MicWit** [symfony/demo#799]
There seems to be something strange going on when loading assets, when using a relative path it is turning it into an absolute path.

I found this as I am running multiple sites on my local apache server, in this case to run the demo site I would run http://localhost/demo/public/

Take for example the build/css/app.css file. It says it cant be found, but it is looking for it at http://localhost/build/css/app.css where it should be looking for it at http://localhost/demo/public/build/css/app.css

I checked the code in the template, and it has the line
`<link rel="stylesheet" href="{{ asset('build/css/app.css') }}">`
which should be correct. Changing this to
`<link rel="stylesheet" href="{{ asset('/build/css/app.css') }}">`
makes no difference as the relative version is outputting the absolute path anyhow.

I have started a new website-skeleton project and thrown the original (relative) link in, and it looks to the correct location (http://localhost/projecttest/public/build/css/app.css).

This would indicate there is something set wrong in the code for the demo app, but I wouldn't have a clue where.

**Comment by stof** [comment]
that's because webpack-encore requires some specific configuration when deploying the project in a subfolder rather than in the document root (which is your case here): https://github.com/symfony/webpack-encore/issues/310#issuecomment-384351850

The webpack config in the demo project is based on deploying the demo with a proper document root (which is the recommended way to deploy a Symfony project anyway).
Note that running the demo using the `bin/console server:start` command works fine, as it uses the proper document root too.

**Comment by javiereguiluz** [comment]
@MicWit that's correct: Encore requires installing Node and Yarn (or npm) first, as explained in https://symfony.com/doc/current/frontend/encore/installation.html

**Comment by javiereguiluz** [comment]
Let's close this because it's more related to Webpack Encore and we can use their repository (https://github.com/symfony/webpack-encore) to track these issues. Thanks!
