### ISSUE TITLE
ManagerInterface or RegistryInterface ? 

### ISSUE THREAD

**Issue by tristanbes** [symfony/demo#809]
Hello,

In the demo, you typehint the [doctrine repositories](https://github.com/symfony/demo/blob/60b80cf271d6f83dcfbb8777544e6b89c3b4f828/src/Repository/PostRepository.php#L33) against `ManagerInterface`, yet in the [documentation](https://symfony.com/doc/4.1/doctrine.html#querying-for-objects-the-repository) it's typed against `RegistryInterface`.
So which one is the correct/recommended one ?

**Comment by sebastianblum** [comment]
in https://github.com/doctrine/DoctrineBundle/blob/master/Repository/ServiceEntityRepository.php you can see, that doctrine uses only ```ManagerRegistry```. So it is enough :-)

**Comment by ogizanagi** [comment]
That's because a commit in doctrine bundle removed the `ManagerRegistry` autowiring alias in favor of `RegistryInterface`. But this was reverted as it was a BC break for no good reason at all. I guess the docs were updated but not reverted since.

https://github.com/doctrine/DoctrineBundle/releases/tag/1.9.1

**Comment by tristanbes** [comment]
Thx
