### ISSUE TITLE
how to genarate bundle?

### ISSUE THREAD

**Issue by wukchao** [symfony/demo#812]
how to genarate bundle for symfony4.1?

**Comment by bocharsky-bw** [comment]
We have a new tool: [MakerBundle](https://github.com/symfony/maker-bundle/issues/87) to generate things. Unfortunately, there's no way to generate bundle with it, but there's a discussion about such command: https://github.com/symfony/maker-bundle/issues/87

For now, the only way is to create the bundle manually, you can copy/paste files structure from another bundle to make it a bit easier

**Comment by javiereguiluz** [comment]
The good news is that if you were thinking about creating bundles for your own code ... that's no longer needed or recommended in modern Symfony apps. If you are creating a third-party bundle, then @bocharsky-bw comment applies.

Since this will be solved outside of this repository, I'm closing this issue. Thanks!
