### ISSUE TITLE
[Question] Using parent route name prefix instead of independant route names

### ISSUE THREAD

**Issue by sundowndev** [symfony/demo#828]
Shouldn't it be a best practice to use the parent Route name prefix for all child routes ?

Like this : 

```php
/**
 * Controller used to manage the application security.
 *
 * @Route("/", name="security_")
 */
class SecurityController extends AbstractController
{

    /**
     * @Route("/login", name="login")
     */
    public function login(AuthenticationUtils $helper): Response
    {
        return $this->render('default/security_login.html.twig', [
            // last username entered by the user (if any)
            'last_email' => $helper->getLastUsername(),
            // last authentication error (if any)
            'error' => $helper->getLastAuthenticationError(),
        ]);
    }
```

Instead of this : 

```php
/**
 * Controller used to manage the application security.
 * @Route("/")
 */
class SecurityController extends AbstractController
{

    /**
     * @Route("/login", name="security_login")
     */
    public function login(AuthenticationUtils $helper): Response
    {
        return $this->render('default/security_login.html.twig', [
            // last username entered by the user (if any)
            'last_email' => $helper->getLastUsername(),
            // last authentication error (if any)
            'error' => $helper->getLastAuthenticationError(),
        ]);
    }
```

**Comment by javiereguiluz** [comment]
Thanks for your proposal! If I'm right, we don't have an official best practice recommendation about this.

My own personal opinion is: never use these parent URLs or routes. The barely save you any typing and they complicate things a lot. For example, if you break the route name in two parts (`security_` in the parent and `login` in the action) you can no longer look for the route in your editor/IDE (you won't find any result for the route name: `security_login`).

The same happens with URLs: you usually only look at actions while developing, so it's easy to forget that `/login` URL is in fact `/security/login`. In this app things are even worse because we have the locale part of the URL being added in some config file, the `/blog` part in the parent controller and the rest of the URL in the actions. It's too confusing :(

But let's wait to read more opinions about this proposal. Thanks!

**Comment by Sundowndev** [comment]
@javiereguiluz I just used a parent route and name prefix on PHPStorm and it seems like the Symfony plugin still finds the route correctly as it supports this usage.

I'm still using this while developing, and waiting for other people to give a review about this!

**Comment by javiereguiluz** [comment]
I'm closing this proposal as "won't fix" because of the received `+1` votes. In any case, thanks for sending this proposal ... and we may implement it in the future (because "best practices" evolve with time).
