### ISSUE TITLE
unused code?

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#850]
is this line 14 "use App\Entity\Comment;" from CommentNotificationSubscriber.php is mandatory?
it works in my side if I comment it

**Comment by yceruto** [comment]
That's used for IDE's autocompletion, see:
https://github.com/symfony/demo/blob/436306118bf202af7ea015d8dcfb3676ebbe2b14/src/EventSubscriber/CommentNotificationSubscriber.php#L50

**Comment by javiereguiluz** [comment]
@lxregistry as Yonel said, that's needed so people using smart IDEs (like PhpStorm) get full autocomplete for all the methods of this variable. IDEs are super smart these days, but sometimes they can't infer the type of some variable, so we must help them with these annotations. But it's OK if you remove them because the app doesn't need them; only your IDE.
