### ISSUE TITLE
Default locale

### ISSUE THREAD

**Issue by rottenberry** [symfony/demo#853]
Is it possible to make a route with a default locale? E.g. '/blog/' instead of '/en/blog/', and '/blog/' leads to '/en/blog/' or something like that. But at the same time another locales in urls must remain properly working. If yes, how to approach that?
Sorry for offtop.

**Comment by bocharsky-bw** [comment]
It can be done in Symfony 4.1, see: https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing

Or see this third-party bundle: https://github.com/schmittjoh/JMSI18nRoutingBundle

**Comment by rottenberry** [comment]
Isn't [https://github.com/schmittjoh/JMSI18nRoutingBundle](https://github.com/schmittjoh/JMSI18nRoutingBundle) outdated? I didn't manage to set it up properly and use with Symfony 4.1.
I'ii try the first solution. Thank you!

**Comment by bocharsky-bw** [comment]
@rottenberry Not sure if it's outdated, but looking at the code I can say it should support Symfony 4.1 as well:
https://github.com/schmittjoh/JMSI18nRoutingBundle/releases/tag/3.0.1
https://github.com/schmittjoh/JMSI18nRoutingBundle/blob/712a76f6fc30127bd73b662a72f59c546201c995/composer.json#L20

If you found any issues - please, report them if they do not exist yet.

**Comment by javiereguiluz** [comment]
As far as I know, it's not possible to define a locale as the default one in the sense that a URL without locale should be treated as an URL with that locale.

Recently (https://github.com/symfony/symfony/pull/27957) we added a feature to fall back from full locale to language-only locale (e.g., use `fr` in URLs even if the locales you manage in the app are `fr_FR`, `fr_BE`, etc.) But it's not the same.

The only current work-around should be to define locale-less routes for each route and then, define a custom Twig function that works similarly to `path()` but it's smarter to not include the locale when the default locale is used.

In any way, let's close this because we won't add this feature in the Symfony Demo app to not complicate things much. Thanks!
