### ISSUE TITLE
[RFC] Workflow demo

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/demo#928]
Hi,

I think it could be very usefull to have an example of the workflow component inside the demo project.

Add a status property on the post, have a listener with guard and personal feature (admin check validation, sending email etc)
(Spec to be decided)

I know there is already https://symfony-workflow-demo.herokuapp.com
but it think having this kind of code example inside this demo app will definitly be better.

I can work on this if this issue is approved 👍 

Thank you,

**Comment by javiereguiluz** [comment]
I have mixed feelings about this ... but I'm mostly 👎 about this.

It's true that a demo of Workflow could be nice. However, given that this app is mostly for newcomers, looking at the source code and finding a complex Workflow-related example instead of the current simple code, would make some people think that Symfony is horribly complex and verbose.

**Comment by jkufner** [comment]
The question is how complex the minimal workflow demo must be to make sense.

I believe it must be much more complex than this simple demo app should be. However, it could be reasonable if if the current simple blog is kept separate and workflow is demonstrated on separate part of the application, properly marked "do NOT start here".

**Comment by noniagriconomie** [comment]
ping, with the next merge of demo on sf 4.3, i think it could be very usefull
i am available to discuss what i called `(Spec to be decided)` in the issue desc
cheers :)

**Comment by javiereguiluz** [comment]
I haven't changed my mind about this :(

Introducing this component in the app will turn the Symfony Demo from *"an easily understandable app to explore Symfony features and possibilities"* to *"an unnecessarily complex app"* which can do more harm than good to us.

Keep in mind that some people still insist that Symfony is "too complex". They are wrong, because they refer to the old Symfony 2.0 versions, which made some things unnecessarily complex. But if we do changes like the one proposed here, they'll have arguments to keep talking about "how complex Symfony is" even for simple things such as a demo blog app. Symfony 4 is great, amazing, fast, minimal. We should showcase that.

**Comment by noniagriconomie** [comment]
@javiereguiluz oki understood
lets onyl refer to doc (+ example) and blog post
thank you!

**Comment by jkufner** [comment]
@noniagriconomie However, it makes sense to have a Workflow Demo App. Something like a next level once a beginer explores this demo app.

**Comment by noniagriconomie** [comment]
there is https://symfony-workflow-demo.herokuapp.com where @lyrixx try to keep it uptodate
it is a nice one IMO, but we can not reference it to the doc as it is not hosted on sf infra

**Comment by lyrixx** [comment]
@javiereguiluz Indeed I keep this "demo" up to date with the framework and there is a lot of resource there. May be it could be nice to add a link to the demo. I know we don't do that usually. WDYT ?

**Comment by noniagriconomie** [comment]
please can you have a look at this https://github.com/symfony/symfony-docs/issues/9834#issuecomment-552105172 @lyrixx @javiereguiluz ?

also the @fabpot tweet https://twitter.com/fabpot/status/1188833580039987202

do you think we can rediscuss/reconsider this issue?

cheers :)

**Comment by noniagriconomie** [comment]
lets close for now :)
