### ISSUE TITLE
[RFC] Use managers more than repositories directly in the controller 

### ISSUE THREAD

**Issue by TheGarious** [symfony/demo#936]
I think is a good idea to implement manager, who is between controller and repository entity.
For search and persist in db.

What do you think?

**Comment by javiereguiluz** [comment]
For this simple app, I think this would be self-defeating because it would complicate the app unnecessarily. We should keep in mind that this is an app mostly designed to show how Symfony works in real apps. But we cannot go deep into more advanced architecture changes (because then some people will ask to transform this into DDD to show how that works, etc.)

But let's wait and read more opinions about this.

**Comment by AlexandrePavy** [comment]
[KISS](https://en.wikipedia.org/wiki/KISS_principle) is a good way to learn fast, I use this project to teach new symfony developers.

Today the project is pretty balanced between symfony best practices / easy implementation.

And for that thanks to you @javiereguiluz (and contributors obviously) you made a great job !

**Comment by javiereguiluz** [comment]
Looking at the upvotes of the previous comment, it seems most people agree with not making this change. So let's close this issue.

However, this doesn't mean that your proposal is wrong. In fact, people can use this app to teach Symfony and then say ... *"this is not entirely right in my opinion ... in real apps you would introduce XXX, so let's do that now"* (where XXX can be "managers", "DDD", "middleware", etc.)
