### ISSUE TITLE
Incoherence in the function name "new("

### ISSUE THREAD

**Issue by jdvellon** [symfony/demo#944]
If new( is a language construct, why call a function like that? It's basically a reserved word. In the IDE it is highlighted as a problem.
I recommend add(

**Comment by rosier** [comment]
Or `create()`

**Comment by stof** [comment]
Most reserved keywords are actually not forbidden anymore in method names since PHP 7

**Comment by javiereguiluz** [comment]
@jdvellon thanks for creating this issue! It helped us review and double check the name of this method. As said above, this shouldn't be a problem since PHP 7.0. Given that this application requires PHP 7.1 or higher, it's OK.

Even if this issue didn't result in a bug fix, we appreciate the time you took to report it and we're looking forward to your future issues and pull requests. Thanks!
