### ISSUE TITLE
Logging in as a normal user redirects to /admin/index

### ISSUE THREAD

**Issue by pgl** [symfony/demo#962]
`SecurityController::index()` contains the following [on line 41](https://github.com/symfony/demo/blob/31ce9eabcb2f4ddd408905a4a673aa61fce41851/src/Controller/SecurityController.php#L41):

`        $this->saveTargetPath($request->getSession(), 'main', $this->generateUrl('admin_index'));`

Unfortunately this redirects *all* logins to the URL of the `admin_index` route - so normal users see a 403 page.

**Comment by javiereguiluz** [comment]
I've been playing with this feature ... and I think it works as expected:

* If you are a normal user and click on "Sign in" in a blog post to add a comment ... you are redirected to the blog post.
* If you are an admin user and do the same ... you get the same result.

* If you are an admin user and click on "Backend" to log in into the admin area ... you are redirected to the admin.
* If you are a normal user and do the same, you see the 403 error because you don't have permission.

This demo app is a bit special because all users can see a big button to try to access to the backend. In real life the backend is not announced to end users ... but they'll get the same 403 if they try to guess the admin URL.

I'm closing as "no fix needed" ... but if I did something wrong in my tests, please tell me and we'll reopen. Thanks!

**Comment by yceruto** [comment]
I was writing a comment about this and I came to the same conclusion as Javier.

**Comment by pgl** [comment]
@javiereguiluz Ah, OK - my apologies for misunderstanding then. Thanks for taking the time to look at it.
