### ISSUE TITLE
Project is not bootable on production

### ISSUE THREAD

**Issue by tristanbes** [symfony/demo#993]
Hello,

Unless I'm missing something, `symfony/demo` is not deployable/bootable on a `APP_ENV=prod` system.

Let me explain why what will happen when you try to deploy the symfony/demo project to your production system:

1/ you'll call `composer install --no-dev`
2/ `cache:clear` will be called because of the `auto-script` present in the `composer.json`
3/ the application will boot because of the cache clear thing, calling `config/bootstrap.php`
4/ no `.env.local.php` will be found because you can't call `composer dump-env` yet, and no dotenv class will be found because `symfony/dotenv` is only installed in `dev` mode.

5/ You'll have a beautiful error [because of what's contained here](https://github.com/symfony/demo/blob/master/config/bootstrap.php#L9-L16)
```
PHP Fatal error: Uncaught RuntimeException: Please run "composer require symfony/dotenv" to load the ".env" files configuring the application. in /home/bas/app_512eafe8-0c2e-4b3e-aa28-778681ffd179/config/bootstrap.php:13
```

As an emergency patch to continue deploy our 4.3 application to PaaS providers, I did require `symfony/dotenv` but it's stupid because my env variable comes from the PaaS itself;

**Comment by javiereguiluz** [comment]
I can confirm this bug. Tristan, thanks for reporting it.

I think this is a bug on our side because both the Symfony skeleton (https://github.com/symfony/skeleton/blob/master/composer.json) and the website skeleton (https://github.com/symfony/website-skeleton/blob/master/composer.json) require this component in prod. So, let's do the same. See #996.
